-- ===========================================================================
-- Author:          Vairavan Chandrasekhar
-- File Name:	    DEV_FED_DDL_DML_BATCH_DB_08012019-01.sql
-- Create date:     07/17/2019
-- Description:     Script to get all the tables and data in Federal EDI schema
-- ===========================================================================

-- This disk group name is only for CERT. For QA and PROD, DBA's need to find this from DB as IP do not have this information
-- select * from dba_temp_files


-- ===========================================================================
--					TABLES
-- ===========================================================================
-- Table 1
CREATE TABLE DEV_FED.TBLALLOWDENYMATCHING (
	SEQ			NUMBER NOT NULL,
	ADDUSER			VARCHAR2(50) DEFAULT 'EDI' NOT NULL,
	ADDDATE			TIMESTAMP (3) DEFAULT SYSTIMESTAMP NOT NULL,
	CHANGEUSER		VARCHAR2(50) DEFAULT 'EDI' NOT NULL,
	CHANGEDATE		TIMESTAMP (3) DEFAULT SYSTIMESTAMP NOT NULL,
	STATUS			CHAR(1) NOT NULL,
	MATCHCLASS		CHAR(3),
	MATCHTYPE		CHAR(1) NOT NULL,
	PRIORITY		FLOAT(126) NOT NULL,
	CLIENTID		VARCHAR2(15) NOT NULL,
	PRODUCTID		VARCHAR2(3) NOT NULL,
	TYPEID			VARCHAR2(3) NOT NULL,
	DESTID			VARCHAR2(15) NOT NULL,
	NAMEPATTERN		VARCHAR2(255) NOT NULL,
	ACTIVE_IND		NUMBER DEFAULT 1
) TABLESPACE LEG_TRACKING_DATA;

-- Primary Key
ALTER TABLE DEV_FED.TBLALLOWDENYMATCHING ADD CONSTRAINT PK_TBLALLOWDENYMATCHING PRIMARY KEY (seq);
CREATE UNIQUE INDEX DEV_FED.IX_TBLALLOWDENYMATCHING1 ON DEV_FED.TBLALLOWDENYMATCHING (MATCHCLASS, MATCHTYPE, CLIENTID, PRODUCTID, TYPEID, DESTID, NAMEPATTERN)  ONLINE TABLESPACE LEG_TRACKING_INDEX;
CREATE INDEX DEV_FED.IX_TBLALLOWDENYMATCHING2 ON DEV_FED.TBLALLOWDENYMATCHING (MATCHCLASS, MATCHTYPE, PRIORITY, CLIENTID, PRODUCTID, TYPEID, DESTID)  ONLINE TABLESPACE LEG_TRACKING_INDEX;
ALTER TABLE DEV_FED.TBLALLOWDENYMATCHING ADD CONSTRAINT IX_TBLALLOWDENYMATCHING1 UNIQUE (MATCHCLASS, MATCHTYPE, CLIENTID, PRODUCTID, TYPEID, DESTID, NAMEPATTERN) USING INDEX;

-- Table 2
CREATE TABLE DEV_FED.TBLCLIENTCOMM (
	CLIENTCOMMSEQ		NUMBER NOT NULL, 
	CLIENTID		VARCHAR2(15) NOT NULL, 
	STATUS			CHAR(1) NOT NULL, 
	LOGIN			VARCHAR2(25),
	PASSWORD		VARCHAR2(25),
	BBSID			CHAR(3),
	COMPRESSIONID		CHAR(3),
	ENCRYPTIONID		CHAR(3),
	PROTOCOLID		CHAR(3),
	ADDUSER			VARCHAR2(50) DEFAULT 'EDI' NOT NULL,
	ADDDATE			TIMESTAMP (3) DEFAULT SYSTIMESTAMP NOT NULL,
	CHANGEUSER		VARCHAR2(50) DEFAULT 'EDI' NOT NULL,
	CHANGEDATE		TIMESTAMP (3) DEFAULT SYSTIMESTAMP NOT NULL,
	PRODUCTID		CHAR(3), 
	CLIENTNAME		VARCHAR2(100), 
	ENCRYPTIONIDOUT		CHAR(3), 
	ALTMAILBOX		VARCHAR2(25), 
	ALTMAILBOXFLAG		CHAR(1) DEFAULT 'N' NOT NULL,
	EXPBSENDTRLFLAG		CHAR(1) DEFAULT 'N' NOT NULL,
	EXPBSTRIPTRLFLAG	CHAR(1) DEFAULT 'N' NOT NULL,
	RENAMEREPORTFLAG	CHAR(1) DEFAULT 'N' NOT NULL,
	CONSTRAINT		IX_TBLCLIENTCOMM1 UNIQUE (CLIENTID) USING INDEX TABLESPACE LEG_TRACKING_INDEX ,
	CONSTRAINT		PK_TBLCLIENTCOMM PRIMARY KEY (CLIENTCOMMSEQ) USING INDEX TABLESPACE LEG_TRACKING_INDEX 
) TABLESPACE LEG_TRACKING_DATA;

-- Table 3
CREATE TABLE DEV_FED.TBLCLIENTENROLLMENT(
	CLIENTSEQ		NUMBER NOT NULL,
	ADDUSER			VARCHAR2(50) DEFAULT 'EDI' NOT NULL,
	ADDDATE			TIMESTAMP (3) DEFAULT SYSTIMESTAMP NOT NULL,
	CHANGEUSER		VARCHAR2(50) DEFAULT 'EDI' NOT NULL,
	CHANGEDATE		TIMESTAMP (3) DEFAULT SYSTIMESTAMP NOT NULL,
	CLIENTID		VARCHAR2(15 BYTE) NOT NULL,
	VWCLIENTID		VARCHAR2(25 BYTE) NOT NULL,
	IMPCONTACT		VARCHAR2(50 BYTE),
	IMPPHONE		VARCHAR2(25 BYTE),
	IMPEMAIL		VARCHAR2(50 BYTE),
	IMPDATE			DATE,
	PSCLIENTID		VARCHAR2(25 BYTE),
	MNEMONIC		VARCHAR2(25 BYTE),
	MIGRATIONDATE		DATE,
	GWCLIENTID		VARCHAR2(25 BYTE),
	GWDESTID		VARCHAR2(25 BYTE),
	RTECLIENTID		VARCHAR2(36 BYTE),
	CLEARINGCLMS		VARCHAR2(6 BYTE),
	CLEARINGELIG		VARCHAR2(6 BYTE),
	CONSTRAINT		IX_TBLCLIENTENROLLMENT1 UNIQUE (CLIENTID) USING INDEX TABLESPACE LEG_TRACKING_INDEX ,
	CONSTRAINT		PK_TBLCLIENTENROLLMENT PRIMARY KEY (CLIENTSEQ) USING INDEX TABLESPACE LEG_TRACKING_INDEX 
) TABLESPACE LEG_TRACKING_DATA;

-- Table 4
CREATE TABLE DEV_FED.TBLDESTTYPES (
	TYPESEQ		NUMBER NOT NULL, 
	ADDUSER		VARCHAR2(50) DEFAULT 'EDI' NOT NULL,
	ADDDATE		TIMESTAMP (3) DEFAULT SYSTIMESTAMP NOT NULL,
	CHANGEUSER	VARCHAR2(50) DEFAULT 'EDI' NOT NULL,
	CHANGEDATE	TIMESTAMP (3) DEFAULT SYSTIMESTAMP NOT NULL,
	TYPEID		CHAR(3 BYTE) NOT NULL, 
	TYPECLASS	VARCHAR2(15 BYTE) NOT NULL, 
	DESCRIPTION	VARCHAR2(100 BYTE),
  	CONSTRAINT	IX_TBLDESTTYPES1 UNIQUE (TYPEID, TYPECLASS) USING INDEX TABLESPACE LEG_TRACKING_INDEX, 
	CONSTRAINT	PK_TBLDESTTYPES PRIMARY KEY (TYPESEQ) USING INDEX TABLESPACE LEG_TRACKING_INDEX 
) TABLESPACE LEG_TRACKING_DATA;
	
INSERT INTO DEV_FED.tbldesttypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLDESTTYPES1.NEXTVAL, 'CLM', 'OUTPUT', 'Claim Output Files');
INSERT INTO DEV_FED.tbldesttypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLDESTTYPES1.NEXTVAL, 'RPT', 'INPUT', 'Report Input Files');
INSERT INTO DEV_FED.tbldesttypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLDESTTYPES1.NEXTVAL, 'INF', 'STATUS', 'Information Status');
INSERT INTO DEV_FED.tbldesttypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLDESTTYPES1.NEXTVAL, 'ERR', 'STATUS', 'Error Status');
INSERT INTO DEV_FED.tbldesttypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLDESTTYPES1.NEXTVAL, 'RCV', 'STATUS', 'Received Status');
INSERT INTO DEV_FED.tbldesttypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLDESTTYPES1.NEXTVAL, 'CMP', 'STATUS', 'Complete Status');
INSERT INTO DEV_FED.tbldesttypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLDESTTYPES1.NEXTVAL, 'RTE', 'STATUS', 'Route Status');
INSERT INTO DEV_FED.tbldesttypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLDESTTYPES1.NEXTVAL, 'ARC', 'STATUS', 'Archive Status');
INSERT INTO DEV_FED.tbldesttypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLDESTTYPES1.NEXTVAL, 'FIX', 'STATUS', 'Fix Status');
INSERT INTO DEV_FED.tbldesttypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLDESTTYPES1.NEXTVAL, 'RSB', 'STATUS', 'Resub Status');
INSERT INTO DEV_FED.tbldesttypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLDESTTYPES1.NEXTVAL, 'PRC', 'STATUS', 'Processing By App');
INSERT INTO DEV_FED.tbldesttypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLDESTTYPES1.NEXTVAL, 'ACK', 'INPUT', 'Acknowledgement Input Files');
INSERT INTO DEV_FED.tbldesttypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLDESTTYPES1.NEXTVAL, 'ZIP', 'STATUS', 'Compression Status');
INSERT INTO DEV_FED.tbldesttypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLDESTTYPES1.NEXTVAL, 'SCR', 'OUTPUT', 'Scrubber Output Files');
INSERT INTO DEV_FED.tbldesttypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLDESTTYPES1.NEXTVAL, 'TRG', 'OUTPUT', 'Scrubber Trigger Files');
INSERT INTO DEV_FED.tbldesttypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLDESTTYPES1.NEXTVAL, 'RPS', 'INPUT', 'Scrubber Input Files');
INSERT INTO DEV_FED.tbldesttypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLDESTTYPES1.NEXTVAL, 'SCB', 'STATUS', 'Scrubber Status');
INSERT INTO DEV_FED.tbldesttypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLDESTTYPES1.NEXTVAL, 'DCR', 'STATUS', 'Encryption Status');
INSERT INTO DEV_FED.tbldesttypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLDESTTYPES1.NEXTVAL, 'TRN', 'STATUS', 'Transmitted Status');
INSERT INTO DEV_FED.tbldesttypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLDESTTYPES1.NEXTVAL, 'ACK', 'STATUS', 'Acknowledged Status');
INSERT INTO DEV_FED.tbldesttypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLDESTTYPES1.NEXTVAL, 'STM', 'OUTPUT', 'Statement Output Files');
INSERT INTO DEV_FED.tbldesttypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLDESTTYPES1.NEXTVAL, 'RMT', 'INPUT', 'Remittance Input Files');
INSERT INTO DEV_FED.tbldesttypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLDESTTYPES1.NEXTVAL, 'TST', 'STATUS', 'Test Status');
INSERT INTO DEV_FED.tbldesttypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLDESTTYPES1.NEXTVAL, 'ELG', 'OUTPUT', 'Eligibility Output Files');
INSERT INTO DEV_FED.tbldesttypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLDESTTYPES1.NEXTVAL, 'ERS', 'INPUT', 'Eligibility Response Files');
INSERT INTO DEV_FED.tbldesttypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLDESTTYPES1.NEXTVAL, 'IMZ', 'OUTPUT', 'Immunization Output Files');
INSERT INTO DEV_FED.tbldesttypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLDESTTYPES1.NEXTVAL, 'LET', 'OUTPUT', 'Letter Output Files');
INSERT INTO DEV_FED.tbldesttypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLDESTTYPES1.NEXTVAL, 'REM', 'OUTPUT', 'Reminder Output Files');
INSERT INTO DEV_FED.tbldesttypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLDESTTYPES1.NEXTVAL, 'CAL', 'OUTPUT', 'Call Output Files');
INSERT INTO DEV_FED.tbldesttypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLDESTTYPES1.NEXTVAL, 'CLN', 'OUTPUT', 'Scrubber Clean Files');
INSERT INTO DEV_FED.tbldesttypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLDESTTYPES1.NEXTVAL, 'OTH', 'OUTPUT', 'Other Files');
INSERT INTO DEV_FED.tbldesttypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLDESTTYPES1.NEXTVAL, 'BAL', 'OUTPUT', 'Online Bill Pay Service');
INSERT INTO DEV_FED.tbldesttypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLDESTTYPES1.NEXTVAL, 'PMT', 'INPUT', 'Emdeon Remittance Input Files');
INSERT INTO DEV_FED.tbldesttypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLDESTTYPES1.NEXTVAL, 'RMT', 'OUTPUT', 'Remittance Output Files');

-- Table 5
CREATE TABLE DEV_FED.TBLPRODUCTS (
	SEQ			NUMBER NOT NULL, 
	ADDUSER			VARCHAR2(50) DEFAULT 'EDI' NOT NULL,
	ADDDATE			TIMESTAMP (3) DEFAULT SYSTIMESTAMP NOT NULL,
	CHANGEUSER		VARCHAR2(50) DEFAULT 'EDI' NOT NULL,
	CHANGEDATE		TIMESTAMP (3) DEFAULT SYSTIMESTAMP NOT NULL,
	PRODUCTID		CHAR(3 BYTE) NOT NULL, 
	BBSID			CHAR(3 BYTE), 
	COMPRESSIONIDOUT	CHAR(3 BYTE), 
	COMPRESSIONIDIN		CHAR(3 BYTE), 
	ENCRYPTIONIDOUT		CHAR(3 BYTE), 
	ENCRYPTIONIDIN		CHAR(3 BYTE), 
	PROTOCOLID		CHAR(3 BYTE), 
	DESCRIPTION		VARCHAR2(100 BYTE) NOT NULL,
  	CONSTRAINT IX_TBLPRODUCTS1 UNIQUE (PRODUCTID) USING INDEX TABLESPACE LEG_TRACKING_INDEX, 
	CONSTRAINT PK_TBLPRODUCTS PRIMARY KEY (SEQ) USING INDEX TABLESPACE LEG_TRACKING_INDEX 
   ) TABLESPACE LEG_TRACKING_DATA;

INSERT INTO DEV_FED.tblproducts(seq, adddate, adduser, changedate, changeuser, PRODUCTID, DESCRIPTION ) VALUES (DEV_FED.SEQ_TBLPRODUCTS1.NEXTVAL, SYSDATE, 'TRACKING', SYSDATE, 'TRACKING', 'CCI', 'CCI');
INSERT INTO DEV_FED.tblproducts(seq, adddate, adduser, changedate, changeuser, PRODUCTID, DESCRIPTION ) VALUES (DEV_FED.SEQ_TBLPRODUCTS1.NEXTVAL, SYSDATE, 'TRACKING', SYSDATE, 'TRACKING', 'CMD', 'CMED');
INSERT INTO DEV_FED.tblproducts(seq, adddate, adduser, changedate, changeuser, PRODUCTID, DESCRIPTION ) VALUES (DEV_FED.SEQ_TBLPRODUCTS1.NEXTVAL, SYSDATE, 'TRACKING', SYSDATE, 'TRACKING', 'CTA', 'CTA');
INSERT INTO DEV_FED.tblproducts(seq, adddate, adduser, changedate, changeuser, PRODUCTID, DESCRIPTION ) VALUES (DEV_FED.SEQ_TBLPRODUCTS1.NEXTVAL, SYSDATE, 'TRACKING', SYSDATE, 'TRACKING', 'D_R', 'DR');
INSERT INTO DEV_FED.tblproducts(seq, adddate, adduser, changedate, changeuser, PRODUCTID, DESCRIPTION ) VALUES (DEV_FED.SEQ_TBLPRODUCTS1.NEXTVAL, SYSDATE, 'TRACKING', SYSDATE, 'TRACKING', 'DM4', 'DM 4000');
INSERT INTO DEV_FED.tblproducts(seq, adddate, adduser, changedate, changeuser, PRODUCTID, DESCRIPTION ) VALUES (DEV_FED.SEQ_TBLPRODUCTS1.NEXTVAL, SYSDATE, 'TRACKING', SYSDATE, 'TRACKING', 'DMO', 'DMO');
INSERT INTO DEV_FED.tblproducts(seq, adddate, adduser, changedate, changeuser, PRODUCTID, DESCRIPTION ) VALUES (DEV_FED.SEQ_TBLPRODUCTS1.NEXTVAL, SYSDATE, 'TRACKING', SYSDATE, 'TRACKING', 'IPM', 'Institutional VWPM');
INSERT INTO DEV_FED.tblproducts(seq, adddate, adduser, changedate, changeuser, PRODUCTID, DESCRIPTION ) VALUES (DEV_FED.SEQ_TBLPRODUCTS1.NEXTVAL, SYSDATE, 'TRACKING', SYSDATE, 'TRACKING', 'KIR', 'Kiron');
INSERT INTO DEV_FED.tblproducts(seq, adddate, adduser, changedate, changeuser, PRODUCTID, DESCRIPTION ) VALUES (DEV_FED.SEQ_TBLPRODUCTS1.NEXTVAL, SYSDATE, 'TRACKING', SYSDATE, 'TRACKING', 'KRE', 'Kredo');
INSERT INTO DEV_FED.tblproducts(seq, adddate, adduser, changedate, changeuser, PRODUCTID, DESCRIPTION ) VALUES (DEV_FED.SEQ_TBLPRODUCTS1.NEXTVAL, SYSDATE, 'TRACKING', SYSDATE, 'TRACKING', 'MED', 'Medfax');
INSERT INTO DEV_FED.tblproducts(seq, adddate, adduser, changedate, changeuser, PRODUCTID, DESCRIPTION ) VALUES (DEV_FED.SEQ_TBLPRODUCTS1.NEXTVAL, SYSDATE, 'TRACKING', SYSDATE, 'TRACKING', 'MSI', 'MSI');
INSERT INTO DEV_FED.tblproducts(seq, adddate, adduser, changedate, changeuser, PRODUCTID, DESCRIPTION ) VALUES (DEV_FED.SEQ_TBLPRODUCTS1.NEXTVAL, SYSDATE, 'TRACKING', SYSDATE, 'TRACKING', 'PAR', 'PAR');
INSERT INTO DEV_FED.tblproducts(seq, adddate, adduser, changedate, changeuser, PRODUCTID, DESCRIPTION ) VALUES (DEV_FED.SEQ_TBLPRODUCTS1.NEXTVAL, SYSDATE, 'TRACKING', SYSDATE, 'TRACKING', 'PMS', 'PM Station');
INSERT INTO DEV_FED.tblproducts(seq, adddate, adduser, changedate, changeuser, PRODUCTID, DESCRIPTION ) VALUES (DEV_FED.SEQ_TBLPRODUCTS1.NEXTVAL, SYSDATE, 'TRACKING', SYSDATE, 'TRACKING', 'PRE', 'Prism Enterprise');
INSERT INTO DEV_FED.tblproducts(seq, adddate, adduser, changedate, changeuser, PRODUCTID, DESCRIPTION ) VALUES (DEV_FED.SEQ_TBLPRODUCTS1.NEXTVAL, SYSDATE, 'TRACKING', SYSDATE, 'TRACKING', 'PRI', 'Prism');
INSERT INTO DEV_FED.tblproducts(seq, adddate, adduser, changedate, changeuser, PRODUCTID, DESCRIPTION ) VALUES (DEV_FED.SEQ_TBLPRODUCTS1.NEXTVAL, SYSDATE, 'TRACKING', SYSDATE, 'TRACKING', 'PRO', 'Promed');
INSERT INTO DEV_FED.tblproducts(seq, adddate, adduser, changedate, changeuser, PRODUCTID, DESCRIPTION ) VALUES (DEV_FED.SEQ_TBLPRODUCTS1.NEXTVAL, SYSDATE, 'TRACKING', SYSDATE, 'TRACKING', 'SDM', 'SDM');
INSERT INTO DEV_FED.tblproducts(seq, adddate, adduser, changedate, changeuser, PRODUCTID, DESCRIPTION ) VALUES (DEV_FED.SEQ_TBLPRODUCTS1.NEXTVAL, SYSDATE, 'TRACKING', SYSDATE, 'TRACKING', 'SEN', 'Sentinal');
INSERT INTO DEV_FED.tblproducts(seq, adddate, adduser, changedate, changeuser, PRODUCTID, DESCRIPTION ) VALUES (DEV_FED.SEQ_TBLPRODUCTS1.NEXTVAL, SYSDATE, 'TRACKING', SYSDATE, 'TRACKING', 'TMD', 'TMED');
INSERT INTO DEV_FED.tblproducts(seq, adddate, adduser, changedate, changeuser, PRODUCTID, DESCRIPTION ) VALUES (DEV_FED.SEQ_TBLPRODUCTS1.NEXTVAL, SYSDATE, 'TRACKING', SYSDATE, 'TRACKING', 'VPM', 'VWPM Intuition - Specialty PM');
INSERT INTO DEV_FED.tblproducts(seq, adddate, adduser, changedate, changeuser, PRODUCTID, DESCRIPTION ) VALUES (DEV_FED.SEQ_TBLPRODUCTS1.NEXTVAL, SYSDATE, 'TRACKING', SYSDATE, 'TRACKING', 'WIS', 'WISDOM');
INSERT INTO DEV_FED.tblproducts(seq, adddate, adduser, changedate, changeuser, PRODUCTID, DESCRIPTION ) VALUES (DEV_FED.SEQ_TBLPRODUCTS1.NEXTVAL, SYSDATE, 'TRACKING', SYSDATE, 'TRACKING', 'VWE', 'Vitalworks Enterprise - CPE - PWPM');
INSERT INTO DEV_FED.tblproducts(seq, adddate, adduser, changedate, changeuser, PRODUCTID, DESCRIPTION ) VALUES (DEV_FED.SEQ_TBLPRODUCTS1.NEXTVAL, SYSDATE, 'TRACKING', SYSDATE, 'TRACKING', 'VWI', 'Vitalworks Enterprise Ideal');
INSERT INTO DEV_FED.tblproducts(seq, adddate, adduser, changedate, changeuser, PRODUCTID, DESCRIPTION ) VALUES (DEV_FED.SEQ_TBLPRODUCTS1.NEXTVAL, SYSDATE, 'TRACKING', SYSDATE, 'TRACKING', 'ADV', 'Advantage');
INSERT INTO DEV_FED.tblproducts(seq, adddate, adduser, changedate, changeuser, PRODUCTID, DESCRIPTION ) VALUES (DEV_FED.SEQ_TBLPRODUCTS1.NEXTVAL, SYSDATE, 'TRACKING', SYSDATE, 'TRACKING', 'MIL', 'Millennium');
INSERT INTO DEV_FED.tblproducts(seq, adddate, adduser, changedate, changeuser, PRODUCTID, DESCRIPTION ) VALUES (DEV_FED.SEQ_TBLPRODUCTS1.NEXTVAL, SYSDATE, 'TRACKING', SYSDATE, 'TRACKING', 'RDC', 'RDC Internal');
INSERT INTO DEV_FED.tblproducts(seq, adddate, adduser, changedate, changeuser, PRODUCTID, DESCRIPTION ) VALUES (DEV_FED.SEQ_TBLPRODUCTS1.NEXTVAL, SYSDATE, 'TRACKING', SYSDATE, 'TRACKING', 'PDS', 'PDS Solution');
INSERT INTO DEV_FED.tblproducts(seq, adddate, adduser, changedate, changeuser, PRODUCTID, DESCRIPTION ) VALUES (DEV_FED.SEQ_TBLPRODUCTS1.NEXTVAL, SYSDATE, 'TRACKING', SYSDATE, 'TRACKING', 'CPM', 'Cerner PM');
INSERT INTO DEV_FED.tblproducts(seq, adddate, adduser, changedate, changeuser, PRODUCTID, DESCRIPTION ) VALUES (DEV_FED.SEQ_TBLPRODUCTS1.NEXTVAL, SYSDATE, 'TRACKING', SYSDATE, 'TRACKING', 'SF ', 'Soarian Financials');
INSERT INTO DEV_FED.tblproducts(seq, adddate, adduser, changedate, changeuser, PRODUCTID, DESCRIPTION ) VALUES (DEV_FED.SEQ_TBLPRODUCTS1.NEXTVAL, SYSDATE, 'TRACKING', SYSDATE, 'TRACKING', 'PAC', 'Long Term Post Acute Care');

-- Table 6
CREATE TABLE DEV_FED.TBLSOURCETYPES (
	TYPESEQ		NUMBER NOT NULL, 
	ADDUSER		VARCHAR2(50) DEFAULT 'EDI' NOT NULL,
	ADDDATE		TIMESTAMP (3) DEFAULT SYSTIMESTAMP NOT NULL,
	CHANGEUSER	VARCHAR2(50) DEFAULT 'EDI' NOT NULL,
	CHANGEDATE	TIMESTAMP (3) DEFAULT SYSTIMESTAMP NOT NULL,
	TYPEID		CHAR(3 BYTE) NOT NULL, 
	TYPECLASS	VARCHAR2(15 BYTE) NOT NULL, 
	DESCRIPTION	VARCHAR2(100 BYTE),
  	CONSTRAINT	IX_TBLSOURCETYPES1 UNIQUE (TYPEID, TYPECLASS) USING INDEX TABLESPACE LEG_TRACKING_INDEX, 
	CONSTRAINT	PK_TBLSOURCETYPES PRIMARY KEY (TYPESEQ) USING INDEX TABLESPACE LEG_TRACKING_INDEX 
) TABLESPACE LEG_TRACKING_DATA;

INSERT INTO DEV_FED.tblsourcetypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLSOURCETYPES1.NEXTVAL, 'CLM', 'INPUT', 'Claim Input Files');
INSERT INTO DEV_FED.tblsourcetypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLSOURCETYPES1.NEXTVAL, 'RPT', 'OUTPUT', 'Report Output Files');
INSERT INTO DEV_FED.tblsourcetypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLSOURCETYPES1.NEXTVAL, 'INF', 'STATUS', 'Information Status');
INSERT INTO DEV_FED.tblsourcetypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLSOURCETYPES1.NEXTVAL, 'ERR', 'STATUS', 'Error Status');
INSERT INTO DEV_FED.tblsourcetypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLSOURCETYPES1.NEXTVAL, 'RCV', 'STATUS', 'Received Status');
INSERT INTO DEV_FED.tblsourcetypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLSOURCETYPES1.NEXTVAL, 'CMP', 'STATUS', 'Complete Status');
INSERT INTO DEV_FED.tblsourcetypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLSOURCETYPES1.NEXTVAL, 'RTE', 'STATUS', 'Route Status');
INSERT INTO DEV_FED.tblsourcetypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLSOURCETYPES1.NEXTVAL, 'ARC', 'STATUS', 'Archive Status');
INSERT INTO DEV_FED.tblsourcetypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLSOURCETYPES1.NEXTVAL, 'FIX', 'STATUS', 'Fix Status');
INSERT INTO DEV_FED.tblsourcetypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLSOURCETYPES1.NEXTVAL, 'RSB', 'STATUS', 'Resub Status');
INSERT INTO DEV_FED.tblsourcetypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLSOURCETYPES1.NEXTVAL, 'PRC', 'STATUS', 'Processing By App');
INSERT INTO DEV_FED.tblsourcetypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLSOURCETYPES1.NEXTVAL, 'ACK', 'OUTPUT', 'Acknowledgement Output Files');
INSERT INTO DEV_FED.tblsourcetypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLSOURCETYPES1.NEXTVAL, 'ZIP', 'STATUS', 'Compression Status');
INSERT INTO DEV_FED.tblsourcetypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLSOURCETYPES1.NEXTVAL, 'SCR', 'INPUT', 'Scrubber Input Files');
INSERT INTO DEV_FED.tblsourcetypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLSOURCETYPES1.NEXTVAL, 'TRG', 'INPUT', 'Trigger Input Files');
INSERT INTO DEV_FED.tblsourcetypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLSOURCETYPES1.NEXTVAL, 'RPS', 'OUTPUT', 'Scrubber Output Files');
INSERT INTO DEV_FED.tblsourcetypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLSOURCETYPES1.NEXTVAL, 'SCB', 'STATUS', 'Scrubber Status');
INSERT INTO DEV_FED.tblsourcetypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLSOURCETYPES1.NEXTVAL, 'DCR', 'STATUS', 'Encryption Status');
INSERT INTO DEV_FED.tblsourcetypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLSOURCETYPES1.NEXTVAL, 'TRN', 'STATUS', 'Transmitted Status');
INSERT INTO DEV_FED.tblsourcetypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLSOURCETYPES1.NEXTVAL, 'ACK', 'STATUS', 'Acknowledged Status');
INSERT INTO DEV_FED.tblsourcetypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLSOURCETYPES1.NEXTVAL, 'STM', 'INPUT', 'Statement Input Files');
INSERT INTO DEV_FED.tblsourcetypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLSOURCETYPES1.NEXTVAL, 'RMT', 'OUTPUT', 'Remittance Output Files');
INSERT INTO DEV_FED.tblsourcetypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLSOURCETYPES1.NEXTVAL, 'TST', 'STATUS', 'Test Status');
INSERT INTO DEV_FED.tblsourcetypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLSOURCETYPES1.NEXTVAL, 'ELG', 'INPUT', 'Eligibility Input Files');
INSERT INTO DEV_FED.tblsourcetypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLSOURCETYPES1.NEXTVAL, 'UNK', 'INPUT', 'Unknown Input Files');
INSERT INTO DEV_FED.tblsourcetypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLSOURCETYPES1.NEXTVAL, 'ERS', 'OUTPUT', 'Eligibility Response Files');
INSERT INTO DEV_FED.tblsourcetypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLSOURCETYPES1.NEXTVAL, 'BUL', 'OUTPUT', 'Bulletin Output Files');
INSERT INTO DEV_FED.tblsourcetypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLSOURCETYPES1.NEXTVAL, 'IMZ', 'INPUT', 'Immunization Input Files');
INSERT INTO DEV_FED.tblsourcetypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLSOURCETYPES1.NEXTVAL, 'LET', 'INPUT', 'Letter Input Files');
INSERT INTO DEV_FED.tblsourcetypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLSOURCETYPES1.NEXTVAL, 'REM', 'INPUT', 'Reminder Input Files');
INSERT INTO DEV_FED.tblsourcetypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLSOURCETYPES1.NEXTVAL, 'CAL', 'INPUT', 'Call Input Files');
INSERT INTO DEV_FED.tblsourcetypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLSOURCETYPES1.NEXTVAL, 'CLN', 'INPUT', 'Scrubber Clean Files');
INSERT INTO DEV_FED.tblsourcetypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLSOURCETYPES1.NEXTVAL, 'BAL', 'INPUT', 'Online Billpay Service');
INSERT INTO DEV_FED.tblsourcetypes(typeseq, typeid, typeclass, description) VALUES (DEV_FED.SEQ_TBLSOURCETYPES1.NEXTVAL, 'PMT', 'OUTPUT', 'Emdeon Remittance Output Files');

-- Table 7
CREATE TABLE DEV_FED.TBLAPPLICATIONS  (
	APPLICATIONSEQ	NUMBER NOT NULL,
	ADDUSER		VARCHAR2(50) DEFAULT 'EDI' NOT NULL,
	ADDDATE		TIMESTAMP (3) DEFAULT SYSTIMESTAMP NOT NULL,
	APPID		VARCHAR2(7) NOT NULL,
	DESCRIPTION	VARCHAR2(100),
	ACTIVE_IND	NUMBER DEFAULT 1,
	CONSTRAINT	PK_TBLAPPLICATIONS PRIMARY KEY (APPLICATIONSEQ) USING INDEX TABLESPACE LEG_TRACKING_INDEX 
) TABLESPACE LEG_TRACKING_DATA;

CREATE UNIQUE INDEX DEV_FED.IX_TBLAPPLICATIONS1 ON DEV_FED.TBLAPPLICATIONS (APPID) ONLINE TABLESPACE LEG_TRACKING_INDEX;
ALTER TABLE DEV_FED.TBLAPPLICATIONS ADD CONSTRAINT IX_TBLAPPLICATIONS1 UNIQUE (APPID) USING INDEX;

INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'WCR','Wildcat BBS Router');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'SFR','SFTP Router');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'SSR','System Source Router');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'MCR','McKesson Router');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'MCF','McKesson FTP');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'SCR','Scrubber Router');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'DER','Dest Router');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'PRC','Processor');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'GWR','GateWorks Router');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'STL','Status Loader');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'RSR','Resub Router');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'RDV','RDC Viewer');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'NDF','NDC FTP');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'HEF','HENN FTP');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'PEF','PerSe FTP');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'GYR','Gateway Router');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'TEF','Televox sFTP');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'S00','svcCommonComponents');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'S01','svcClientFileRouterIn');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'S02','svcClaimFmtRouterIn');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'S03','svcClaimFmtRouterScrIn');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'S04','svcClaimFmtRouterOut');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'S05','svc8372837Eval');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'S06','svc8372837ScrOut');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'S07','svcENSF2ENSFEval');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'S08','svcENSF2ENSFScrOut');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'S09','svcUB2UBEval');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'S10','svcUB2UBScrOut');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'S11','svcScrubberIOIn');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'S12','svcScrubberIOOut');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'S13','svcPrintFmtRouterIn');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'S14','svcPrint2PrintMckEval');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'S15','svcPrint2PrintNDCEval');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'S16','svcPrint2PrintPerSeEval');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'S17','svcCallFmtRouterIn');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'S18','svcCall2CallTelevoxEval');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'S19','svcImmunizationFmtRouterIn');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'S20','svcImz2ImzHennepinEval');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'S21','svcEligibilityFmtRouterIn');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'S22','svc2702270Eval');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'S23','svcClient2Dest');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'S24','svcDestFileRouterOut');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'S25','svcArchiveRouter');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'F2Q','File 2 Queue Router');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'S26','svc8372837Split');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'S27','svcNewChildFile');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'S28','svcDestFileRouterIn');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'S29','svcDest2Client');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'S30','svcClientFileRouterOut');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'S31','svcTVSReportProcess');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'S32','svcPERSEReportProcess');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'S33','svcNDCReportSplit');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'S34','svcNDCReportProcess');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'S35','svc627411ReportIn');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'S36','svc627411ReportANSI');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'S37','svc627411ReportData');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'PIF','Practice Insight sFTP');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'S38','svcPrint2PrintEXPBEval');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'EBF','ExpressBill sFTP');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'S39','svcPRAINReportProcess');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'S40','svcEXPBReportProcess');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'S41','svcEMDReportProcess');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'GEF','Gateway EDI sFTP');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'ECLMSPL','Edifecs Claims Split');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'ED1','837D_Route');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'ED2','TM_Ack_Route');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'ED3','Error_Route');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'ED4','Edifecs 837D Route 4');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'ER1','835D_Route_ER1');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'ER2','TM_Ack_Route_ER2');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'ER3','Error_Route_ER3');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'ER4','Edifecs 835D Route 4');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'EIPSPLT','837IP_Split_Route');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'APF','Apex sFTP');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'ERMFARC','835_File_Archival_Route');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'ERMTM','835_TM_Route');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'ERMTMAK','835_TM_ACK_Route');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'EPRACK','HDXTS_NX12_PRAIN_ACK_Route');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'EPRAKER','HDXTS_NX12_PRAIN_ACK_Error_Route');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'ENXDFF1','HDXTS_NONX12_DFF_REPORTS_MAIN_Route');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'ENXDFF9','HDXTS_NONX12_DFF_REPORTS_ERROR_Route');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'ENXMA12','HDXTS_NONX12_MCKESSON_ACKS_Route');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'ENXRACK','HDXTS_NONX12_REPORTS_ACKS_MAIN_Route');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'ENXPFF9','HDXTS_NONX12_PFF_REPORTS_ERROR_Route');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'EIPMAIN','837_Gateway');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'EIPSISA','837IP_Route');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'EIPMISA','837IP_ISA_Split_Route');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'ENXPACK','Edifecs Non-X12 Partner Acknowledgements');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'ENXSTLT','Edifecs Non-X12 Statements and Letters');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'MEF','Megas sFTP');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'EPAKX12','HDXTS_X12_PARTNER_ACKS_Route');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'EPAKERR','HDXTS_X12_PARTNER_ACKS_Error_Route');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'EAKSRDM','HDXTS_X12_PARTNER_ACKS_SenderReceiver_Route');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'EIPSRDM','837IP_SenderReceiver_Route');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'EIPERR','837IP_Error_Route');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'EIPTMAK','837IP_TM_ACK_Route');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'ERMMAIN','835_Main_Route');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'ERMCHK','835_Remit_Check_Route');
INSERT INTO DEV_FED.TBLAPPLICATIONS (applicationseq, appid,description) VALUES (DEV_FED.SEQ_TBLAPPLICATIONS1.NEXTVAL,'ERMERR','835_Error_Route');

-- Table 8
CREATE TABLE DEV_FED.TBLDESTCOMM (
	DESTCOMMSEQ		NUMBER NOT NULL, 
	ADDUSER			VARCHAR2(50) DEFAULT 'EDI' NOT NULL,
	ADDDATE			TIMESTAMP (3) DEFAULT SYSTIMESTAMP NOT NULL,
	CHANGEUSER		VARCHAR2(50) DEFAULT 'EDI' NOT NULL,
	CHANGEDATE		TIMESTAMP (3) DEFAULT SYSTIMESTAMP NOT NULL,
	DESTID			VARCHAR2(15 BYTE) NOT NULL, 
	DESTNAME		VARCHAR2(100 BYTE), 
	STATUS			CHAR(1 BYTE) NOT NULL, 
	LOGIN			VARCHAR2(25 BYTE), 
	PASSWORD		VARCHAR2(25 BYTE), 
	COMPRESSIONIDIN		CHAR(3 BYTE), 
	COMPRESSIONIDOUT	CHAR(3 BYTE), 
	ENCRYPTIONIDIN		CHAR(3 BYTE), 
	ENCRYPTIONIDOUT		CHAR(3 BYTE), 
	PROTOCOLID		CHAR(3 BYTE), 
	PRODUCTID		CHAR(3 BYTE), 
	CONSTRAINT		IX_TBLDESTCOMM1 UNIQUE (DESTID) USING INDEX TABLESPACE LEG_TRACKING_INDEX , 
	CONSTRAINT		PK_TBLDESTCOMM PRIMARY KEY (DESTCOMMSEQ) USING INDEX TABLESPACE LEG_TRACKING_INDEX
  )TABLESPACE LEG_TRACKING_DATA;

-- Table 9
CREATE TABLE DEV_FED.TBLDESTENROLLMENT 
   (	DESTSEQ			NUMBER NOT NULL, 
	ADDUSER			VARCHAR2(50) DEFAULT 'EDI' NOT NULL,
	ADDDATE			TIMESTAMP (3) DEFAULT SYSTIMESTAMP NOT NULL,
	CHANGEUSER		VARCHAR2(50) DEFAULT 'EDI' NOT NULL,
	CHANGEDATE		TIMESTAMP (3) DEFAULT SYSTIMESTAMP NOT NULL,
	DESTID			VARCHAR2(15 BYTE) NOT NULL, 
	VWDESTID		VARCHAR2(25 BYTE) NOT NULL, 
	IMPCONTACT		VARCHAR2(50 BYTE), 
	IMPPHONE		VARCHAR2(25 BYTE), 
	IMPEMAIL		VARCHAR2(50 BYTE), 
	IMPDATE			DATE, 
	PSDESTID		VARCHAR2(25 BYTE), 
	MNEMONIC		VARCHAR2(25 BYTE), 
	MIGRATIONDATE		DATE, 
	GWDESTID		VARCHAR2(25 BYTE), 
	CONSTRAINT		IX_TBLDESTENROLLMENT1 UNIQUE (DESTID) USING INDEX TABLESPACE LEG_TRACKING_INDEX , 
        CONSTRAINT		PK_TBLDESTENROLLMENT PRIMARY KEY (DESTSEQ) USING INDEX TABLESPACE LEG_TRACKING_INDEX 
  )TABLESPACE LEG_TRACKING_DATA ;

CREATE INDEX DEV_FED.IX_TBLDESTENROLLMENT2 ON DEV_FED.TBLDESTENROLLMENT (VWDESTID) TABLESPACE LEG_TRACKING_INDEX;
CREATE INDEX DEV_FED.IX_TBLDESTENROLLMENT3 ON DEV_FED.TBLDESTENROLLMENT (IMPDATE) TABLESPACE LEG_TRACKING_INDEX;
CREATE INDEX DEV_FED.IX_TBLDESTENROLLMENT4 ON DEV_FED.TBLDESTENROLLMENT (PSDESTID) TABLESPACE LEG_TRACKING_INDEX;
CREATE INDEX DEV_FED.IX_TBLDESTENROLLMENT5 ON DEV_FED.TBLDESTENROLLMENT (MNEMONIC) TABLESPACE LEG_TRACKING_INDEX;

-- Table 10
CREATE TABLE DEV_FED.TBLOPTIONS
   (	SEQ		NUMBER NOT NULL, 
	ADDUSER		VARCHAR2(50) DEFAULT 'TRACKING',
	ADDDATE		TIMESTAMP (3) DEFAULT SYSTIMESTAMP,
	CHANGEUSER	VARCHAR2(50) DEFAULT 'TRACKING',
	CHANGEDATE	TIMESTAMP (3) DEFAULT SYSTIMESTAMP,
	GROUPID		VARCHAR2(15 BYTE) NOT NULL, 
	TYPEID		VARCHAR2(3 BYTE) NOT NULL, 
	DESCRIPTION	VARCHAR2(100 BYTE) NOT NULL, 
	 CONSTRAINT	IX_TBLOPTIONS1 UNIQUE (GROUPID, TYPEID) USING INDEX TABLESPACE LEG_TRACKING_INDEX, 
	 CONSTRAINT	PK_TBLOPTIONS PRIMARY KEY (SEQ) USING INDEX TABLESPACE LEG_TRACKING_INDEX 
   ) TABLESPACE LEG_TRACKING_DATA ;

INSERT INTO DEV_FED.tbloptions(seq, adddate, adduser, changedate, changeuser, groupid, typeid, description ) VALUES (DEV_FED.SEQ_TBLOPTIONS1.NEXTVAL, SYSDATE, 'TRACKING', SYSDATE, 'TRACKING', 'STATUS', 'A', 'Active'); 
INSERT INTO DEV_FED.tbloptions(seq, adddate, adduser, changedate, changeuser, groupid, typeid, description ) VALUES (DEV_FED.SEQ_TBLOPTIONS1.NEXTVAL, SYSDATE, 'TRACKING', SYSDATE, 'TRACKING', 'STATUS', 'I', 'Inactive'); 
INSERT INTO DEV_FED.tbloptions(seq, adddate, adduser, changedate, changeuser, groupid, typeid, description ) VALUES (DEV_FED.SEQ_TBLOPTIONS1.NEXTVAL, SYSDATE, 'TRACKING', SYSDATE, 'TRACKING', 'STATUS', 'T', 'Test'); 
INSERT INTO DEV_FED.tbloptions(seq, adddate, adduser, changedate, changeuser, groupid, typeid, description ) VALUES (DEV_FED.SEQ_TBLOPTIONS1.NEXTVAL, SYSDATE, 'TRACKING', SYSDATE, 'TRACKING', 'BBS', 'GWK', 'GateWorks'); 
INSERT INTO DEV_FED.tbloptions(seq, adddate, adduser, changedate, changeuser, groupid, typeid, description ) VALUES (DEV_FED.SEQ_TBLOPTIONS1.NEXTVAL, SYSDATE, 'TRACKING', SYSDATE, 'TRACKING', 'BBS', 'FTP', 'FTP SFTP'); 
INSERT INTO DEV_FED.tbloptions(seq, adddate, adduser, changedate, changeuser, groupid, typeid, description ) VALUES (DEV_FED.SEQ_TBLOPTIONS1.NEXTVAL, SYSDATE, 'TRACKING', SYSDATE, 'TRACKING', 'BBS', 'PRI', 'Prism'); 
INSERT INTO DEV_FED.tbloptions(seq, adddate, adduser, changedate, changeuser, groupid, typeid, description ) VALUES (DEV_FED.SEQ_TBLOPTIONS1.NEXTVAL, SYSDATE, 'TRACKING', SYSDATE, 'TRACKING', 'BBS', 'RAP', 'RapidServices'); 
INSERT INTO DEV_FED.tbloptions(seq, adddate, adduser, changedate, changeuser, groupid, typeid, description ) VALUES (DEV_FED.SEQ_TBLOPTIONS1.NEXTVAL, SYSDATE, 'TRACKING', SYSDATE, 'TRACKING', 'BBS', 'VIT', 'Vitalworks'); 
INSERT INTO DEV_FED.tbloptions(seq, adddate, adduser, changedate, changeuser, groupid, typeid, description ) VALUES (DEV_FED.SEQ_TBLOPTIONS1.NEXTVAL, SYSDATE, 'TRACKING', SYSDATE, 'TRACKING', 'COMPRESSION', 'NON', 'Not Compressed'); 
INSERT INTO DEV_FED.tbloptions(seq, adddate, adduser, changedate, changeuser, groupid, typeid, description ) VALUES (DEV_FED.SEQ_TBLOPTIONS1.NEXTVAL, SYSDATE, 'TRACKING', SYSDATE, 'TRACKING', 'COMPRESSION', 'GZP', 'GZIP'); 
INSERT INTO DEV_FED.tbloptions(seq, adddate, adduser, changedate, changeuser, groupid, typeid, description ) VALUES (DEV_FED.SEQ_TBLOPTIONS1.NEXTVAL, SYSDATE, 'TRACKING', SYSDATE, 'TRACKING', 'COMPRESSION', 'ZIP', 'PKZIP'); 
INSERT INTO DEV_FED.tbloptions(seq, adddate, adduser, changedate, changeuser, groupid, typeid, description ) VALUES (DEV_FED.SEQ_TBLOPTIONS1.NEXTVAL, SYSDATE, 'TRACKING', SYSDATE, 'TRACKING', 'ENCRYPTION', 'NON', 'Not Encrypted'); 
INSERT INTO DEV_FED.tbloptions(seq, adddate, adduser, changedate, changeuser, groupid, typeid, description ) VALUES (DEV_FED.SEQ_TBLOPTIONS1.NEXTVAL, SYSDATE, 'TRACKING', SYSDATE, 'TRACKING', 'ENCRYPTION', 'VWC', 'VWCrypto'); 
INSERT INTO DEV_FED.tbloptions(seq, adddate, adduser, changedate, changeuser, groupid, typeid, description ) VALUES (DEV_FED.SEQ_TBLOPTIONS1.NEXTVAL, SYSDATE, 'TRACKING', SYSDATE, 'TRACKING', 'PROTOCOL', 'ANY', 'Any Type'); 
INSERT INTO DEV_FED.tbloptions(seq, adddate, adduser, changedate, changeuser, groupid, typeid, description ) VALUES (DEV_FED.SEQ_TBLOPTIONS1.NEXTVAL, SYSDATE, 'TRACKING', SYSDATE, 'TRACKING', 'PROTOCOL', 'XMO', 'XModem'); 
INSERT INTO DEV_FED.tbloptions(seq, adddate, adduser, changedate, changeuser, groupid, typeid, description ) VALUES (DEV_FED.SEQ_TBLOPTIONS1.NEXTVAL, SYSDATE, 'TRACKING', SYSDATE, 'TRACKING', 'PROTOCOL', 'KER', 'Kermit'); 
INSERT INTO DEV_FED.tbloptions(seq, adddate, adduser, changedate, changeuser, groupid, typeid, description ) VALUES (DEV_FED.SEQ_TBLOPTIONS1.NEXTVAL, SYSDATE, 'TRACKING', SYSDATE, 'TRACKING', 'BBS', 'GWY', 'Gateway'); 
INSERT INTO DEV_FED.tbloptions(seq, adddate, adduser, changedate, changeuser, groupid, typeid, description ) VALUES (DEV_FED.SEQ_TBLOPTIONS1.NEXTVAL, SYSDATE, 'TRACKING', SYSDATE, 'TRACKING', 'BBS', 'PIF', 'Practice Insight SFTP'); 
INSERT INTO DEV_FED.tbloptions(seq, adddate, adduser, changedate, changeuser, groupid, typeid, description ) VALUES (DEV_FED.SEQ_TBLOPTIONS1.NEXTVAL, SYSDATE, 'TRACKING', SYSDATE, 'TRACKING', 'BBS', 'DFT', 'Dialup FTP SFTP'); 

-- ===========================================================================
--					TRIGGERS
-- ===========================================================================

--  DDL for Trigger TRG_TBLALLOWDENYMATCHING1
CREATE OR REPLACE TRIGGER DEV_FED.TRG_TBLALLOWDENYMATCHING1
BEFORE INSERT OR UPDATE
ON DEV_FED.tblAllowDenyMatching
FOR EACH ROW
DECLARE
BEGIN
  :new.Status := UPPER(:new.Status);
  :new.MatchClass := UPPER(:new.MatchClass);
  :new.MatchType := UPPER(:new.MatchType);
  :new.ClientID := UPPER(:new.ClientID);
	:new.ProductID := UPPER(:new.ProductID);
	:new.TypeID := UPPER(:new.TypeID);
	:new.DestID := UPPER(:new.DestID);
END;
/

ALTER TRIGGER DEV_FED.TRG_TBLALLOWDENYMATCHING1 ENABLE;

--  DDL for Trigger TRG_TBLAPPLICATIONS1
CREATE OR REPLACE TRIGGER DEV_FED.TRG_TBLAPPLICATIONS1
BEFORE INSERT OR UPDATE
ON DEV_FED.tblApplications
FOR EACH ROW
DECLARE
BEGIN
  :new.AppID := UPPER(:new.AppID);
END;

/
ALTER TRIGGER DEV_FED.TRG_TBLAPPLICATIONS1 ENABLE;

--  DDL for Trigger TRG_TBLCLIENTCOMM1
CREATE OR REPLACE TRIGGER DEV_FED.TRG_TBLCLIENTCOMM1
BEFORE INSERT OR UPDATE
ON DEV_FED.tblClientComm
FOR EACH ROW
DECLARE
BEGIN
	:new.ClientID := UPPER(:new.ClientID);
	:new.Status := UPPER(:new.Status);
	:new.BBSID := UPPER(:new.BBSID);
	:new.CompressionID := UPPER(:new.CompressionID);
	:new.EncryptionID := UPPER(:new.EncryptionID);
	:new.ProtocolID := UPPER(:new.ProtocolID);
	:new.ProductID := UPPER(:new.ProductID);
	:new.ClientName := UPPER(:new.ClientName);
	:new.EncryptionIDOut := UPPER(:new.EncryptionIDOut);
END;

/
ALTER TRIGGER DEV_FED.TRG_TBLCLIENTCOMM1 ENABLE;

--  DDL for Trigger TRG_TBLCLIENTENROLLMENT1
CREATE OR REPLACE TRIGGER DEV_FED.TRG_TBLCLIENTENROLLMENT1
BEFORE INSERT OR UPDATE
ON DEV_FED.tblClientEnrollment
FOR EACH ROW
DECLARE
BEGIN
	:new.ClientID := UPPER(:new.ClientID);
	:new.VWClientID := UPPER(:new.VWClientID);
	:new.ImpContact := UPPER(:new.ImpContact);
	:new.ImpPhone := UPPER(:new.ImpPhone);
	:new.ImpEmail := UPPER(:new.ImpEmail);
	:new.PSClientID := UPPER(:new.PSClientID);
	:new.Mnemonic := UPPER(:new.Mnemonic);
END;

/
ALTER TRIGGER DEV_FED.TRG_TBLCLIENTENROLLMENT1 ENABLE;

--  DDL for Trigger TRG_TBLDESTTYPES1
CREATE OR REPLACE TRIGGER DEV_FED.TRG_TBLDESTTYPES1
BEFORE INSERT OR UPDATE
ON DEV_FED.tblDestTypes
FOR EACH ROW
DECLARE
BEGIN
	:new.TypeID := UPPER(:new.TypeID);
	:new.TypeClass := UPPER(:new.TypeClass);
END;

/
ALTER TRIGGER DEV_FED.TRG_TBLDESTTYPES1 ENABLE;

--  DDL for Trigger TRG_TBLOPTIONS1
CREATE OR REPLACE TRIGGER DEV_FED.TRG_TBLOPTIONS1
BEFORE INSERT OR UPDATE
ON DEV_FED.tblOptions
FOR EACH ROW
DECLARE
BEGIN

  :new.GroupID := UPPER(:new.GroupID);
  :new.TypeID := UPPER(:new.TypeID);  
END;
/
ALTER TRIGGER DEV_FED.TRG_TBLOPTIONS1 ENABLE;

--  DDL for Trigger TRG_TBLPRODUCTS1
CREATE OR REPLACE TRIGGER DEV_FED.TRG_TBLPRODUCTS1
BEFORE INSERT OR UPDATE
ON DEV_FED.tblProducts
FOR EACH ROW
DECLARE
BEGIN
	:new.ProductID := UPPER(:new.ProductID);
	:new.BBSID := UPPER(:new.BBSID);
	:new.CompressionIDOut := UPPER(:new.CompressionIDOut);
	:new.CompressionIDIn := UPPER(:new.CompressionIDIn);
	:new.EncryptionIDOut := UPPER(:new.EncryptionIDOut);
	:new.EncryptionIDIn := UPPER(:new.EncryptionIDIn);
	:new.ProtocolID := UPPER(:new.ProtocolID);
END;

/
ALTER TRIGGER DEV_FED.TRG_TBLPRODUCTS1 ENABLE;

--  DDL for Trigger TRG_TBLSOURCETYPES1
CREATE OR REPLACE TRIGGER DEV_FED.TRG_TBLSOURCETYPES1
BEFORE INSERT OR UPDATE
ON DEV_FED.tblSourceTypes
FOR EACH ROW
DECLARE
BEGIN
	:new.TypeID := UPPER(:new.TypeID);
	:new.TypeClass := UPPER(:new.TypeClass);
END;

/
ALTER TRIGGER DEV_FED.TRG_TBLSOURCETYPES1 ENABLE;


--  DDL for Trigger TRG_TBLDESTCOMM1
CREATE OR REPLACE TRIGGER DEV_FED.TRG_TBLDESTCOMM1
BEFORE INSERT OR UPDATE
ON DEV_FED.tblDestComm
FOR EACH ROW
DECLARE
BEGIN
	:new.DestID := UPPER(:new.DestID);
	:new.DestName := UPPER(:new.DestName);
	:new.Status := UPPER(:new.Status);
	:new.CompressionIDIn := UPPER(:new.CompressionIDIn);
	:new.CompressionIDOut := UPPER(:new.CompressionIDOut);
	:new.EncryptionIDIn := UPPER(:new.EncryptionIDIn);
	:new.EncryptionIDOut := UPPER(:new.EncryptionIDOut);
	:new.ProtocolID := UPPER(:new.ProtocolID);
	:new.ProductID := UPPER(:new.ProductID);
END;
/

--  DDL for Trigger TRG_TBLDESTENROLLMENT1
CREATE OR REPLACE TRIGGER DEV_FED.TRG_TBLDESTENROLLMENT1 
BEFORE INSERT OR UPDATE
ON DEV_FED.tblDestEnrollment
FOR EACH ROW
DECLARE
BEGIN 
	:new.DestID := UPPER(:new.DestID);
	:new.VWDestID := UPPER(:new.VWDestID);
	:new.ImpContact := UPPER(:new.ImpContact);
	:new.ImpPhone := UPPER(:new.ImpPhone);
	:new.ImpEmail := UPPER(:new.ImpEmail);
	:new.PSDestID := UPPER(:new.PSDestID);
	:new.Mnemonic := UPPER(:new.Mnemonic);
END;

/
ALTER TRIGGER DEV_FED.TRG_TBLDESTENROLLMENT1 ENABLE;
